# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jKKIrbWZpr7pVNsPZ3yq_wH16zo3vLO
"""

def multiply(x, y):

    return x * y

def divide(x, y):

    if y == 0:
        return "Error: Division by zero is not allowed."
    return x / y

def subtract(x, y):

    return x - y

def main():
    print("This is a Simple Calculator!")
    print("Choose an operation to do:")
    print("1. Multiplication (*)")
    print("2. Division (/)")
    print("3. Subtraction (-)")
    print("Enter 'q' to quit.")

    while True:
        choice = input("\nEnter your choice (1/2/3 or q to quit): ")

        if choice.lower() == 'q':
            print("calculator is closing")
            break

        if choice not in ['1', '2', '3']:
            print("Invalid choice. Please select 1, 2, 3, or 'q' to quit.")
            continue

        try:
            # Asking for two number
            num1 = float(input("Enter the first number: "))
            num2 = float(input("Enter the second number: "))
        except ValueError:
            print("Invalid input. Please enter numeric values.")
            continue


        if choice == '1':
            result = multiply(num1, num2)
            operator = '*'
        elif choice == '2':
            result = divide(num1, num2)
            operator = '/'
        elif choice == '3':
            result = subtract(num1, num2)
            operator = '-'
        else:
            result = "Unknown operation."

        # for result.
        print(f"\nResult: {num1} {operator} {num2} = {result}")

if __name__ == "__main__":
    main()